runtime: nodejs16
service: express

vpc_access_connector:
  name: projects/auth-generalate/locations/asia-northeast1/connectors/cloudfunctions-connector

env_variables:
  #DBのアクセス情報 (cloudSQL）
  DB_KEY1: "quickstart-user"
  DB_KEY2: "password"
  DB_KEY3: "quickstart_db"
  DB_KEY4: "/cloudsql/auth-generalate:asia-northeast2:quickstart-instance"

  #firebaseアクセス情報
  REACT_APP_APIKEY: "AIzaSyBRwnkVhqY7EkV38wbyTu6NujPAgUAcOFg"
  REACT_APP_AUTHDOMAIN: "auth-generalate.firebaseapp.com"
  REACT_APP_PROJECT_ID: "auth-generalate"
  REACT_APP_STORAGE_BUCKET: "auth-generalate.appspot.com"
  REACT_APP_MESSAGING_SENDER_ID: "217710701450"
  REACT_APP_APP_ID: "1:217710701450:web:54648f840fddffa6ff7673"
